name: SWEML_310
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - affine=2.4.0
  - aiobotocore=2.13.0
  - aiodns=3.0.0
  - aiohttp=3.9.5
  - aioitertools=0.11.0
  - aiosignal=1.3.1
  - appdirs=1.4.4
  - arrow-cpp=14.0.2
  - asttokens=2.4.1
  - async-retriever=0.17.1
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - beautifulsoup4=4.12.3
  - blas=1.0
  - blosc=1.21.5
  - boost-cpp=1.82.0
  - boto3=1.34.106
  - botocore=1.34.106
  - bounded-pool-executor=0.0.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2026.1.4
  - cachetools=5.3.3
  - cairo=1.18.0
  - cattrs=24.1.2
  - certifi=2026.1.4
  - cffi=1.16.0
  - cfitsio=4.3.1
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.10.19
  - cryptography=42.0.8
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - cytoolz=0.12.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - earthaccess=0.9.0
  - earthengine-api=0.1.407
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=4.3.2
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.4.1
  - fsspec=2024.6.0
  - future=1.0.0
  - gdal=3.8.1
  - geojson=3.1.0
  - geopandas-base=1.1.2
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - google-api-core=2.19.0
  - google-api-python-client=2.133.0
  - google-auth=2.30.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.17.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.0
  - googleapis-common-protos=1.63.1
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - httplib2=0.22.0
  - icu=73.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipython=8.25.0
  - ipywidgets=8.1.3
  - isodate=0.6.1
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - json-c=0.17
  - jupyterlab_widgets=3.0.11
  - kealib=1.5.3
  - keyutils=1.6.1
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20211102.0
  - libaec=1.1.3
  - libarchive=3.7.4
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-devel=1.82.0
  - libboost-headers=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcurl=8.8.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.19
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc=7.2.0
  - libgcc-ng=13.2.0
  - libgdal=3.8.1
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libhwloc=2.9.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=3.20.3
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.15.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lxml=5.2.2
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.5
  - matplotlib-inline=0.1.7
  - minizip=4.0.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - multimethod=1.11.2
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - netcdf4=1.6.5
  - nettle=3.6
  - networkx=3.3
  - nspr=4.35
  - nss=3.100
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=1.7.4
  - owslib=0.35.0
  - pandas=2.2.2
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - poppler=23.12.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - pqdm=0.2.0
  - proj=9.3.1
  - prompt-toolkit=3.0.47
  - proto-plus=1.23.0
  - protobuf=3.20.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycares=4.0.0
  - pycparser=2.22
  - pygeoogc=0.17.1
  - pygeoutils=0.17.1
  - pygments=2.18.0
  - pygridmet=0.17.1
  - pyogrio=0.7.2
  - pyopenssl=24.0.0
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-cmr=0.11.0
  - python-dateutil=2.9.0.post0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - requests-cache=1.3.0
  - rsa=4.9.1
  - s2n=1.3.27
  - s3fs=2024.6.0
  - s3transfer=0.10.1
  - setuptools=69.5.1
  - shapely=2.0.4
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.3
  - suds-jurko=0.6
  - sympy=1.13.3
  - tbb=2021.8.0
  - tiledb=2.18.2
  - tinynetrc=1.3.1
  - tk=8.6.14
  - toolz=1.1.0
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzcode=2024a
  - tzdata=2024a
  - ujson=5.10.0
  - ulmo=0.8.8
  - uriparser=0.9.8
  - uritemplate=4.1.1
  - urllib3=2.2.1
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - wrapt=1.16.0
  - x264=1!161.3030
  - xerces-c=3.2.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohttp-client-cache==0.12.3
      - aiosqlite==0.20.0
      - annotated-types==0.7.0
      - bleach==6.1.0
      - blosc2==2.7.1
      - bokeh==3.6.0
      - branca==0.8.0
      - click==8.1.7
      - click-plugins==1.1.1
      - colorcet==3.1.0
      - contextily==1.6.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - earthpy==0.9.4
      - exceptiongroup==1.2.1
      - fiona==1.9.6
      - folium==0.17.0
      - fonttools==4.53.0
      - geographiclib==2.0
      - geopandas==0.14.4
      - geopy==2.4.1
      - h5netcdf==1.4.0
      - h5py==3.12.1
      - holoviews==1.19.1
      - hvplot==0.11.0
      - hydroeval==0.1.0
      - hydrotools==2.2.2
      - hydrotools--restclient==3.1.0
      - hydrotools-caches==0.1.3
      - hydrotools-events==1.1.6
      - hydrotools-metrics==1.3.3
      - hydrotools-nwis-client==3.3.1
      - hydrotools-nwm-client==5.0.3
      - imageio==2.36.1
      - ipykernel==6.29.4
      - joblib==1.4.2
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - linkify-it-py==2.0.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mercantile==1.2.1
      - msgpack==1.1.0
      - ndindex==1.9.2
      - numexpr==2.10.1
      - nvidia-nccl-cu12==2.23.4
      - packaging==24.1
      - panel==1.5.2
      - param==2.1.1
      - planetary-computer==1.0.0
      - platformdirs==4.2.2
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pystac==1.10.1
      - pystac-client==0.8.2
      - python-dotenv==1.0.1
      - python-forge==18.6.0
      - pyviz-comms==3.0.3
      - pyzmq==26.0.3
      - qrcode==8.0
      - rasterio==1.3.10
      - rasterstats==0.19.0
      - referencing==0.35.1
      - rioxarray==0.15.5
      - rpds-py==0.18.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - simplejson==3.19.2
      - tables==3.10.1
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tornado==6.4.1
      - uc-micro-py==1.0.3
      - url-normalize==1.4.3
      - vincent==0.4.4
      - webencodings==0.5.1
      - xarray==2024.6.0
      - xgboost==2.1.1
      - xyzservices==2024.9.0

