name: SWEML_310_v2
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - jmespath=1.0.1
  - libbrotlicommon=1.0.9
  - protobuf=3.20.3
  - xorg-kbproto=1.0.7
  - lxml=5.2.2
  - expat=2.6.2
  - mkl_random=1.2.4
  - blas=1.0
  - font-ttf-ubuntu=0.83
  - pyyaml=6.0.2
  - affine=2.4.0
  - multimethod=1.11.2
  - cuda-version=12.6
  - toolz=1.0.0
  - xorg-libsm=1.2.4
  - icu=73.2
  - aws-c-mqtt=0.7.13
  - libgettextpo-devel=0.22.5
  - frozenlist=1.4.1
  - libsqlite=3.46.0
  - nest-asyncio=1.6.0
  - libnghttp2=1.58.0
  - grpcio=1.48.2
  - libpq=16.3
  - libthrift=0.15.0
  - netcdf4=1.6.5
  - libevent=2.1.12
  - libuuid=2.38.1
  - lz4-c=1.9.4
  - nettle=3.6
  - libzip=1.10.1
  - pyparsing=3.1.2
  - pyu2f=0.1.5
  - libboost=1.82.0
  - torchvision=0.19.1
  - xorg-libxext=1.3.4
  - numpy=1.26.4
  - postgresql=16.3
  - pillow=10.3.0
  - fonts-conda-ecosystem=1
  - font-ttf-inconsolata=3.000
  - _libgcc_mutex=0.1
  - lzo=2.10
  - mkl-service=2.4.0
  - s2n=1.3.27
  - suds-jurko=0.6
  - xorg-libxrender=0.9.11
  - libzlib=1.2.13
  - comm=0.2.2
  - libgdal=3.8.1
  - minizip=4.0.6
  - libgcc-ng=13.2.0
  - async-retriever=0.17.1
  - poppler=23.12.0
  - pygeoogc=0.17.1
  - xerces-c=3.2.5
  - llvm-openmp=15.0.7
  - fontconfig=2.14.2
  - libnetcdf=4.9.2
  - aioitertools=0.11.0
  - colorama=0.4.6
  - cuda-cudart=11.8.89
  - krb5=1.21.2
  - googleapis-common-protos=1.63.1
  - cuda-nvrtc=11.8.89
  - libcusolver=11.4.1.48
  - libkml=1.3.0
  - google-crc32c=1.1.2
  - glog=0.5.0
  - mpfr=4.2.1
  - python-cmr=0.11.0
  - torchaudio=2.4.1
  - libnsl=2.0.1
  - xorg-libice=1.1.1
  - aws-c-event-stream=0.2.15
  - s3transfer=0.10.1
  - platformdirs=4.3.8
  - tqdm=4.66.4
  - nss=3.100
  - libgfortran-ng=13.2.0
  - hdf4=4.2.15
  - libstdcxx-ng=13.2.0
  - gmpy2=2.1.5
  - py3dep=0.17.1
  - yaml=0.2.5
  - msgpack-python=1.0.8
  - libnpp=11.8.0.86
  - filelock=3.16.1
  - mkl=2023.1.0
  - pcre2=10.42
  - freexl=2.0.0
  - isodate=0.6.1
  - ncurses=6.4
  - zarr=2.18.3
  - google-auth=2.30.0
  - numexpr=2.10.1
  - cuda-libraries=11.8.0
  - libcblas=3.9.0
  - poppler-data=0.4.12
  - snappy=1.1.10
  - aiosignal=1.3.1
  - lerc=4.0.0
  - tk=8.6.14
  - aws-c-io=0.13.10
  - xorg-renderproto=0.11.1
  - aws-c-cal=0.5.20
  - ca-certificates=2026.1.4
  - itsdangerous=2.2.0
  - xz=5.4.6
  - yarl=1.9.4
  - boost-cpp=1.82.0
  - libarchive=3.7.4
  - libcufile=1.11.1.6
  - aiohttp=3.9.5
  - pytorch-cuda=11.8
  - bzip2=1.0.8
  - kealib=1.5.3
  - libbrotlienc=1.0.9
  - readline=8.2
  - future=1.0.0
  - cryptography=42.0.8
  - cuda-cupti=11.8.87
  - fonts-conda-forge=1
  - geos=3.12.1
  - httplib2=0.22.0
  - librttopo=1.1.0
  - libblas=3.9.0
  - libgcc=7.2.0
  - sympy=1.13.3
  - pysocks=1.7.1
  - pyasn1=0.6.0
  - aws-c-common=0.8.5
  - appdirs=1.4.4
  - tzdata=2024a
  - aws-checksums=0.1.13
  - xorg-libxau=1.0.11
  - cairo=1.18.0
  - cattrs=24.1.2
  - google-auth-httplib2=0.2.0
  - libcrc32c=1.1.2
  - numcodecs=0.13.0
  - wcwidth=0.2.13
  - gmp=6.3.0
  - xorg-xproto=7.0.31
  - libexpat=2.6.2
  - pickleshare=0.7.5
  - ulmo=0.8.8
  - proj
  - torchtriton=3.0.0
  - tiledb=2.18.2
  - aws-c-http=0.6.25
  - earthaccess=0.9.0
  - uriparser=0.9.8
  - libbrotlidec=1.0.9
  - pip=24.0
  - brotli=1.0.9
  - google-resumable-media=2.7.0
  - libxcb=1.15
  - libnvjpeg=11.9.0.86
  - parso=0.8.4
  - traitlets=5.14.3
  - python-dateutil=2.9.0post0
  - libgettextpo=0.22.5
  - aws-c-s3=0.1.51
  - libasprintf=0.22.5
  - packaging=25.0
  - cytoolz=0.12.3
  - google-api-core=2.19.0
  - zlib=1.2.13
  - liblapack=3.9.0
  - pthread-stubs=0.4
  - pytorch-mutex=1.0
  - pandas=2.2.2
  - geopandas-base=1.1.1
  - gettext=0.22.5
  - pygeoutils=0.17.1
  - ptyprocess=0.7.0
  - google-cloud-storage=2.17.0
  - proto-plus=1.23.0
  - pqdm=0.2.0
  - google-cloud-core=2.4.1
  - _openmp_mutex=4.5
  - giflib=5.2.2
  - libxslt=1.1.39
  - openssl=3.3.1
  - openjpeg=2.5.2
  - cfitsio=4.3.1
  - gdal=3.8.1
  - libpng=1.6.43
  - font-ttf-source-code-pro=2.038
  - botocore=1.34.106
  - blosc=1.21.5
  - libcurand=10.3.7.77
  - mkl_fft=1.3.8
  - uritemplate=4.1.1
  - gflags=2.2.2
  - pexpect=4.9.0
  - python_abi=3.10
  - abseil-cpp=20211102.0
  - lame=3.100
  - matplotlib-inline=0.1.7
  - fonts-anaconda=1
  - nspr=4.35
  - libasprintf-devel=0.22.5
  - aiobotocore=2.13.0
  - libffi=3.4.4
  - s3fs=2024.6.0
  - asciitree=0.3.3
  - libiconv=1.17
  - async-timeout=4.0.3
  - libprotobuf=3.20.3
  - libspatialite=5.1.0
  - libdeflate=1.19
  - cftime=1.6.4
  - libxcrypt=4.4.36
  - bounded-pool-executor=0.0.3
  - aiosqlite=0.20.0
  - libtiff=4.6.0
  - numpy-base=1.26.4
  - xorg-xextproto=7.3.0
  - shapely=2.0.4
  - libcublas=11.11.3.6
  - zstd=1.5.6
  - cuda-nvtx=11.8.86
  - ld_impl_linux-64=2.38
  - defusedxml=0.7.1
  - libcurl=8.8.0
  - cuda-runtime=11.8.0
  - gettext-tools=0.22.5
  - multidict=6.0.5
  - libaec=1.1.3
  - mpmath=1.3.0
  - pyasn1-modules=0.4.0
  - python=3.10.13
  - re2=2022.04.01
  - snuggs=1.4.7
  - mpc=1.3.1
  - libcusparse=11.7.5.86
  - bottleneck=1.4.2
  - owslib=0.34.1
  - utf8proc=2.6.1
  - aiodns=3.0.0
  - c-ares=1.28.1
  - libedit=3.1.20230828
  - geotiff=1.7.1
  - requests-cache=1.2.1
  - pycparser=2.22
  - prompt_toolkit=3.0.47
  - font-ttf-dejavu-sans-mono=2.37
  - grpc-cpp=1.48.2
  - lcms2=2.16
  - networkx=3.3
  - fsspec=2024.6.0
  - sqlite=3.45.3
  - libssh2=1.11.0
  - tzcode=2024a
  - freetype=2.12.1
  - ujson=5.10.0
  - libjpeg-turbo=3.0.0
  - libcufft=10.9.0.58
  - xorg-libx11=1.8.9
  - libglib=2.78.4
  - pixman=0.43.2
  - fasteners=0.19
  - hdf5=1.14.3
  - aws-c-auth=0.6.19
  - aws-crt-cpp=0.18.16
  - tbb=2021.8.0
  - wrapt=1.16.0
  - intel-openmp=2023.1.0
  - libxml2=2.12.7
  - libev=4.33
  - rsa=4.9
  - libgfortran5=13.2.0
  - gtest=1.14.0
  - arrow-cpp=14.0.2
  - geojson=3.1.0
  - json-c=0.17
  - pyarrow=14.0.2
  - keyutils=1.6.1
  - tinynetrc=1.3.1
  - gnutls=3.6.13
  - libgomp=13.2.0
  - openh264=2.1.1
  - libwebp-base=1.4.0
  - pydaymet=0.17.1
  - python-tzdata=2024.1
  - pytz=2024.1
  - cligj=0.7.2
  - pyopenssl=24.0.0
  - aws-sdk-cpp=1.10.55
  - cachetools=5.3.3
  - pycares=4.0.0
  - brotli-python=1.0.9
  - pytorch=2.4.1
  - xorg-libxdmcp=1.1.3
  - pyogrio=0.7.2
  - ffmpeg=4.3
  - libboost-headers=1.82.0
  - orc=1.7.4
  - google-api-python-client=2.133.0
  - aws-c-compression=0.2.16
  - boto3=1.34.106
  - aws-c-sdkutils=0.1.6
  - wheel=0.43.0
  - pygridmet
  - dask
